data:
  weather_path: "./data/weather_data.csv"
  population_path: "./data/population_data.csv"
  selected_weather_columns:
    - datetime
    - temp
    - humidity
    - precip

model:
  target: 1
  batch_size: 32
  seq_length: 365
  hidden_size: 128
  num_layers: 3
  output_size: 1
  learning_rate: 0.0001
  num_epochs: 20
  train_sizes: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]