data:
  weather_path: "https://raw.githubusercontent.com/Juanfra21/mosquito-population-model/main/data/weather_data.csv"
  population_path: "https://raw.githubusercontent.com/Juanfra21/mosquito-population-model/main/data/population_data.csv"
  selected_weather_columns:
    - "datetime"
    - "temp"
    - "humidity"
    - "precip"

model_1:
  target: 1
  batch_size: 32
  seq_length: 52
  hidden_size: 8
  num_layers: 2
  output_size: 1
  learning_rate: 0.005
  num_epochs: 30
  train_size: 0.8
  population_rolling_window: 4

model_2:
  target: 1
  batch_size: 16
  seq_length: 52
  hidden_size: 8
  num_layers: 4
  output_size: 1
  learning_rate: 0.005
  num_epochs: 30
  train_size: 0.8
  population_rolling_window: 4

model_3:
  target: 1
  batch_size: 64
  seq_length: 52
  hidden_size: 8
  num_layers: 2
  output_size: 1
  learning_rate: 0.005
  num_epochs: 30
  train_size: 0.8
  population_rolling_window: 4

model_4:
  target: 1
  batch_size: 32
  seq_length: 52
  hidden_size: 8
  num_layers: 2
  output_size: 1
  learning_rate: 0.005
  num_epochs: 30
  train_size: 0.8
  population_rolling_window: 4

model_5:
  target: 1
  batch_size: 32
  seq_length: 52
  hidden_size: 8
  num_layers: 2
  output_size: 1
  learning_rate: 0.005
  num_epochs: 30
  train_size: 0.8
  population_rolling_window: 4

model_key: 'model_5'
data_testing_path: 'data/mosquito_pop_weather_data.csv'