data:
  weather_path: "./data/weather_data.csv"
  population_path: "./data/population_data.csv"
  selected_weather_columns:
    - datetime
    - temp
    - humidity
    - precip

model:
  target: 1
  batch_size: 512
  seq_length: 365
  hidden_size: 16
  num_layers: 2
  output_size: 1
  learning_rate: 0.0005
  num_epochs: 30
  train_sizes: [0.2, 0.5, 0.8]