data:
  weather_path: "./data/weather_data.csv"
  population_path: "./data/population_data.csv"
  selected_weather_columns:
    - datetime
    - temp
    - humidity
    - precip

model:
  target: 1
  batch_size: 64
  seq_length: 365
  hidden_size: 64
  num_layers: 2
  output_size: 1
  learning_rate: 0.00001
  num_epochs: 50
  train_size: 0.8